name: 'mgr_repo'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]

models:
  mgr_repo:
    staging:
      +materialized: view
      +schema: stg
    intermediate:
      +materialized: ephemeral
      +schema: int
    marts:
      +materialized: table
      +schema: marts
      dimensions:
        +tags: ["dimension"]
      facts:
        +materialized: incremental
        +tags: ["fact"]
